version: "3.8"

services:
  frontend:
    build: ./Frontend
    ports:
      - "3000:80"
    restart: unless-stopped

  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    volumes:
      - ~/.aws:/root/.aws:ro
    env_file:
      - .env

  failover-monitor:
    build: ./FailoverMonitor 
    restart: unless-stopped
    volumes:
      - ~/.aws:/root/.aws:ro
    env_file:
      - .env 